sudo: true

dist: trusty

language: php

php:
  - 7.4
  - 7.3
  - 7.2
  - 7.1
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

install: travis_retry composer install

before_script: sudo locale-gen uk_UA.UTF-8

script: composer test

jobs:
  allow_failures:
    - php: nightly
    - php: 8.0

  include:
    - stage: Code Coverage
      php: 7.4
      before_script:
        - mkdir -p build/logs
      script: composer cover
      after_script: composer coveralls
    - stage: Code Standarts
      php: 7.4
      script: composer check-style
